[package]
name = "chip8rs"
version = "0.1.0"
authors = ["Antoine Busch <antoine.busch@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap="3"
minifb = "0.20"
log = "0.4.0"
env_logger = "0.9"
rand="0.8"
